run_tests:
	make -C tests && sudo bash uartboot.sh ./tests/firmware/firmware.bin
run_coremark:
	make -C coremark && sudo bash uartboot.sh ./coremark/coremark.bin 
run_renderer:
	make -C pingo_renderer && sudo bash uartboot.sh ./pingo_renderer/sdboot.bin
